@extends('default.default')
@section('titleContent')
    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Nama</th>
                <th>NIM/NIDN</th>
                <th>E-mail</th>
            </tr>
        </thead>
    </table>
@endsection